"""empty message

Revision ID: 30fd99581a02
Revises: 
Create Date: 2019-08-03 21:38:21.189406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fd99581a02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('addtime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_auth_addtime'), 'auth', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_addtime'), table_name='auth')
    op.drop_column('auth', 'addtime')
    # ### end Alembic commands ###
