"""empty message

Revision ID: ddd837f7dc7b
Revises: 30fd99581a02
Create Date: 2019-08-05 20:55:09.024452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd837f7dc7b'
down_revision = '30fd99581a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_ibfk_2', 'movie', type_='foreignkey')
    op.drop_column('movie', 'moviecol_id')
    op.add_column('moviecol', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moviecol', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moviecol', type_='foreignkey')
    op.drop_column('moviecol', 'movie_id')
    op.add_column('movie', sa.Column('moviecol_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('movie_ibfk_2', 'movie', 'moviecol', ['moviecol_id'], ['id'])
    # ### end Alembic commands ###
